CREATE TABLE `users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `last_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `users`
(`name`, `last_name`)
VALUES
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg'),
('Pedro', 'Sola'),
('Lionel', 'Messi'),
('Papá', 'Dios'),
('Freddy', 'Vega'),
('Mark', 'Zuckerberg');